# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID19.3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID19.3


pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

end
